I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 168, in script
    $AICommand=command.ComplexCommand()
  File "game/script.rpy", line 168, in <module>
    $AICommand=command.ComplexCommand()
TypeError: __init__() takes exactly 4 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 168, in script
    $AICommand=command.ComplexCommand()
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-7.3.5-sdk/renpy/python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 168, in <module>
    $AICommand=command.ComplexCommand()
TypeError: __init__() takes exactly 4 arguments (1 given)

Darwin-19.6.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
Gates of Galloo 1.0
Tue Nov 24 12:40:21 2020
